### ISSUE TITLE
Curve Logging output not expected for linear data

### ISSUE THREAD

**Issue by noci0001** [Geotab/curve#2]
**GOAL:** apply curve logging to a time series of 10 data points.

**CONTEXT:** I am working on integrating curve-logging into the Fleet Management Blueprint, in order to do so I am retrieving data from the Kuksa.val databroker and then adapting them to be compliant for the curve logging to work properly.

**EXPECTED OUTPUT:** if the time series is greater than 3 points, the output should convey the same trend/shape/pattern with fewer points. From my perspective it is safe to assume that you would always have a returned reduced vector of at least 3 datapoints.

**CURRENT OUTPUT:** The current output is a vector with only one point.

For example, assuming a linear time series of 10 data points from 0.0 to 9.0 I would expect an output of the first point, the last and one in between (because it's linear). However, what I get as an output is only the last point.

Here you can see the output from the example you provide in the repo (scalar.rs). The only change is the data that was made linear for ease in debugging.

_For instance, the real life example would equate to: a truck starts at 0 seconds at speed 0 and after 10 seconds of linear increment it arrives at 10mph. Before sending this information to our database we want to curve log it._

![scalar.rs](https://github.com/Geotab/curve/assets/79120220/0949dbb6-2eef-413b-b0f7-2f021ff8e5b7)

Sidenote: If you want access to my code, I will add you to the repo.

FYI: @tguild

**Comment by tguild** [comment]
@yuhanlin-geotab would be able to answer better than I. Perhaps it considers the initial state of 0 known/recorded and in that case would only need to know one more point to be able to draw a straight line not three. I would try with some more varied and non-linear data.

**Comment by yuhanlin-geotab** [comment]
The reason why `curve.rs` doesn't save the 1st point of the curve is because there are many situations where the 1st point of the curve buffer is the last saved point of the last buffer. For example, this happens when the `run_on` flag is set. Since we don't want to log the same point twice, we don't save the 1st point automatically. If we do want to save the 1st point of the curve, the caller needs to save the point manually.

**Comment by noci0001** [comment]
Your insights were very useful, thank you both!
